### ISSUE TITLE
Incompatibility with pyglet resource loading.

### ISSUE THREAD

**Issue by caffeinepills** [Ryex/Rabbyt#1]
Not sure if this branch is a continuation of Rabbyt or was just made for the conversion. I'm sure this library support is dead, but thought I'd mention this here in case someone with issues ended up here.

Either way, I thought I'd mention here that there is an incompatibility issue with Rabbyt and Pyglet. The recommended way to load images for Pyglet is the pyglet.resource.image function. However, this can cause textures to be loaded as GL_TEXTURE_RECTANGLE_ARB or GL_TEXTURE_RECTANGLE_NV instead of GL_TEXTURE_2D. Those new texture modes are used on newer cards so they do not have to support power of 2 and also eliminates some rendering issues. They will be used if your card supports them. However, Rabbyt forces GL_TEXTURE_2D for each sprite. Due to this, your textures will appear either invisible or white. It would probably require a small rewrite to support them. The only way I found around this was to use the less efficient loading of pyglet.image.load which isn't ideal.

**Comment by Ryex** [comment]
Hmm, when I made this port I never intended to support it much outside of efforts on my own projects. However this seems like a valid improvement and you have actually diagnosed the problem for me so I'll see what I can do.

**Comment by caffeinepills** [comment]
Ah, I completely forgot about this, didn't expect someone to reply. Did you ever find time to implement this in your project as well?

**Comment by Ryex** [comment]
there is a new branch texture_mode ive made a pull request for #2

I've made some edits that SHOULD fix the problem. at least I didn't encounter problems on my end with the latest pyglet runn the basic4_pyglet example . if you can, try out that branch and let me know. if it works for you I'll do some optimizations so it's not checking for the extensions every god dame frame.

**Comment by caffeinepills** [comment]
I'm having a hell of a time trying to get it to compile on Windows.

EDIT:
I finally got it recognizing the extensions by adding:
`#include <GL/glext.h>`
Into the include_gl.h
It seems my compiler didn't include the headers for the newer GLSL stuff.
However it still won't compile due to this error.

```
rabbyt._rabbyt.obj : error LNK2019: unresolved external symbol _glGetStringi@8 referenced in function ___pyx_pf_6rabbyt_7_rabbyt_4_gl_get_ext_i

build\lib.win32-2.7\rabbyt\_rabbyt.pyd : fatal error LNK1120: 1 unresolved externals
```

I checked and it's in the header file. Any ideas?

**Comment by Ryex** [comment]
there is a library that it needs to link to where _glGetStringi actually has an object. missing link dependency. sadly I'm not all that familiar with how opengl is distributed on windows.

cursory googling reveals that windows by default doesn't expose opengl 3.0 things in it's headers
https://www.opengl.org/discussion_boards/archive/index.php/t-180709.html

I'm not sure how to overcome this as most compiles will require the user to download external headers and libraries and set up their include paths properly.

**Comment by caffeinepills** [comment]
Thanks for the link, I'll give it a shot tonight. Although if I use glew to compile it, I'd assume I'd need to include those dll's with my install. 

I had a thought that may or may not work. Pyglet contains the target in it's texture class. (texture.target) which determines if its GL_TEXTURE_RECTANGLE_ARB, GL_TEXTURE_RECTANGLE_NV, or GL_TEXTURE_2D. If you make each sprite have the target saved (default as GL_TEXTURE_2D) and when you set the texture see if it has a target property that differs,, do you think that might work? It might remove some dependencies on checking through the Cython files.

**Comment by Ryex** [comment]
I think I'v figures out a way to do it. I'll use pyglet to figur out what the texture target should be just like rabbyt already uses pyglet to load the texture, which is the source of the problem.

**Comment by Ryex** [comment]
ok, attempt it now. instead of querying extensions itself now the code detects if pyglet is in use and calls into it. it will also pull the texture target used out of the pyglet texture directly.  this also fixes the early inefficiency.

**Comment by caffeinepills** [comment]
Sorry for the delay, I've been busy lately but had time today. :)

I have just tried it and it compiled without any issues at all! However, trying to run anything produces the following error:

```
C:\Users\Admin\Desktop\Rabbyt-master\Rabbyt-texture_mode\examples>C:\Users\Admin\Desktop\Rabbyt-master\Rabbyt-texture_mode\examples\basic4_pyglet.py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Rabbyt-master\Rabbyt-texture_mode\examples\basic4_pyglet.py", line 36, in <module>
    car.render()
  File "rabbyt\rabbyt._sprites.pyx", line 461, in rabbyt._sprites.cSprite.render (rabbyt\rabbyt._sprites.c:4006)
  File "rabbyt\rabbyt._sprites.pyx", line 402, in rabbyt._sprites.cSprite._render (rabbyt\rabbyt._sprites.c:3523)
AttributeError: 'Sprite' object has no attribute '_target'

C:\Users\Admin\Desktop\Rabbyt-master\Rabbyt-texture_mode\examples>
```

**Comment by Ryex** [comment]
Are you sure that you did a clean pull and compile free of any changes you
may of made? That line is blank in my source and it compiles fine in Linux
and Windows on my end.

**Comment by caffeinepills** [comment]
Oops, I was totally on the wrong directory, sorry about that! After doing this, everything compiles without issues and after testing, seems to work properly, with both pyglet and pygame! Awesome!

The only issue I've found so far is that if you import both pygame and pyglet, it will produce a black screen no matter what.  Not sure if this is an issue for you, but just thought I'd mention it.

**Comment by Ryex** [comment]
ok then, I'll merge #2 into master. I'll be bumping the version and adding travis and appvayer CI in a new branch tonight as well. I noticed that the test are actually failing on the almost equal assertions I suspect that is because of type conversions the compiler is doing in the 64bit system so I'll be looking into that as well.
